// StrataHQ - Comprehensive Mock Data

import type {
  User,
  UserRole,
  Property,
  MaintenanceRequest,
  Violation,
  Meeting,
  Task,
  Document,
  Poll,
  Amenity,
  Booking,
  ForumPost,
  ServiceProvider,
  EmergencyContact,
  DashboardStats,
  Activity,
} from './types';

// Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Sarah Mitchell',
    email: 'sarah.mitchell@email.com',
    role: 'council_member',
    unit: '405',
    phone: '(604) 555-0123',
    avatar: '',
    isCouncilMember: true,
    councilPosition: 'President',
    joinedDate: '2021-03-15',
    status: 'active',
  },
  {
    id: '2',
    name: 'David Chen',
    email: 'david.chen@email.com',
    role: 'council_member',
    unit: '302',
    phone: '(604) 555-0124',
    isCouncilMember: true,
    councilPosition: 'Treasurer',
    joinedDate: '2021-06-20',
    status: 'active',
  },
  {
    id: '3',
    name: 'Linda Rodriguez',
    email: 'linda.rodriguez@email.com',
    role: 'property_manager',
    phone: '(604) 555-0125',
    joinedDate: '2020-01-10',
    status: 'active',
  },
  {
    id: '4',
    name: 'James Thompson',
    email: 'james.thompson@email.com',
    role: 'resident',
    unit: '508',
    phone: '(604) 555-0126',
    joinedDate: '2022-09-01',
    status: 'active',
  },
  {
    id: '5',
    name: 'Emily Foster',
    email: 'emily.foster@email.com',
    role: 'resident',
    unit: '612',
    phone: '(604) 555-0127',
    joinedDate: '2023-01-15',
    status: 'active',
  },
];

export const mockProperty: Property = {
  id: 'prop-1',
  name: 'Harborview Towers',
  address: '123 Marine Drive, Vancouver, BC V7V 1K9',
  units: 120,
  type: 'residential',
  yearBuilt: 2018,
};

// Maintenance Requests
export const mockMaintenanceRequests: MaintenanceRequest[] = [
  {
    id: 'req-001',
    title: 'Parking Garage Lighting Malfunction',
    description: 'Several lights in P2 parking level are flickering or completely out. Safety concern for residents.',
    category: 'electrical',
    priority: 'urgent',
    status: 'in_progress',
    location: 'Parking Level P2',
    submittedBy: '4',
    submittedDate: '2024-02-15T09:30:00Z',
    assignedTo: '3',
    assignedVendor: 'vendor-002',
    dueDate: '2024-02-18T17:00:00Z',
    estimatedCost: 2500,
    attachments: [
      {
        id: 'att-001',
        name: 'parking-lights.jpg',
        type: 'image/jpeg',
        size: 245000,
        url: '/attachments/parking-lights.jpg',
        uploadedDate: '2024-02-15T09:30:00Z',
      },
    ],
    timeline: [
      {
        id: 'tl-001',
        title: 'Request Submitted',
        description: 'Maintenance request created',
        date: '2024-02-15T09:30:00Z',
        type: 'status_change',
        user: 'James Thompson',
      },
      {
        id: 'tl-002',
        title: 'Under Review',
        description: 'Property manager reviewing request',
        date: '2024-02-15T10:15:00Z',
        type: 'status_change',
        user: 'Linda Rodriguez',
      },
      {
        id: 'tl-003',
        title: 'Assigned to Vendor',
        description: 'Assigned to Bright Sparks Electrical',
        date: '2024-02-15T14:00:00Z',
        type: 'assignment',
        user: 'Linda Rodriguez',
      },
    ],
    comments: [
      {
        id: 'comment-001',
        author: 'Linda Rodriguez',
        content: 'Contacted electrician, they will inspect tomorrow morning.',
        createdDate: '2024-02-15T14:05:00Z',
      },
    ],
  },
  {
    id: 'req-002',
    title: 'Lobby Water Fountain Not Working',
    description: 'Main lobby water fountain has been out of service for 3 days.',
    category: 'plumbing',
    priority: 'medium',
    status: 'under_review',
    location: 'Main Lobby',
    submittedBy: '5',
    submittedDate: '2024-02-16T11:20:00Z',
    assignedTo: '3',
    dueDate: '2024-02-23T17:00:00Z',
    estimatedCost: 800,
  },
  {
    id: 'req-003',
    title: 'Elevator #2 Making Strange Noise',
    description: 'Residents have reported grinding noise coming from elevator #2 between floors 4-8.',
    category: 'other',
    priority: 'high',
    status: 'approved',
    location: 'Elevator #2',
    submittedBy: '1',
    submittedDate: '2024-02-14T16:45:00Z',
    assignedTo: '3',
    dueDate: '2024-02-20T17:00:00Z',
    estimatedCost: 3500,
  },
  {
    id: 'req-004',
    title: 'Garden Area Sprinkler System Leak',
    description: 'Sprinkler head damaged, causing water to spray onto walkway.',
    category: 'landscaping',
    priority: 'low',
    status: 'submitted',
    location: 'East Garden',
    submittedBy: '4',
    submittedDate: '2024-02-17T08:15:00Z',
  },
];

// Violations
export const mockViolations: Violation[] = [
  {
    id: 'vio-001',
    title: 'Unauthorized Balcony Renovation',
    description: 'Unit 1205 installed glass panels on balcony without council approval.',
    category: 'alteration',
    status: 'investigating',
    severity: 'major',
    reportedBy: '1',
    reportedDate: '2024-02-10T14:00:00Z',
    violator: 'Unit 1205 Owner',
    unit: '1205',
    location: 'Unit 1205 Balcony',
    evidence: [
      {
        id: 'ev-001',
        name: 'balcony-alteration.jpg',
        type: 'image/jpeg',
        size: 312000,
        url: '/evidence/balcony-alteration.jpg',
        uploadedDate: '2024-02-10T14:00:00Z',
      },
    ],
    fineAmount: 500,
    comments: [
      {
        id: 'com-001',
        author: 'Sarah Mitchell',
        content: 'Sent formal notice requesting removal or approval process.',
        createdDate: '2024-02-12T09:00:00Z',
        isInternal: true,
      },
    ],
  },
  {
    id: 'vio-002',
    title: 'Repeated Noise Complaints',
    description: 'Multiple residents reported loud music after 11 PM on weekends from Unit 803.',
    category: 'noise',
    status: 'warning_issued',
    severity: 'moderate',
    reportedBy: 'Multiple Residents',
    reportedDate: '2024-02-08T23:30:00Z',
    violator: 'Unit 803 Resident',
    unit: '803',
    location: 'Unit 803',
    actionTaken: 'First written warning issued',
  },
  {
    id: 'vio-003',
    title: 'Improper Garbage Disposal',
    description: 'Resident leaving garbage bags in hallway instead of using designated disposal room.',
    category: 'common_area_misuse',
    status: 'resolved',
    severity: 'minor',
    reportedBy: '3',
    reportedDate: '2024-01-25T07:15:00Z',
    violator: 'Unit 405 Resident',
    unit: '405',
    location: 'Floor 4 Hallway',
    resolution: 'Resident educated on proper disposal procedures. No further incidents.',
    resolvedDate: '2024-01-28T10:00:00Z',
  },
];

// Meetings
export const mockMeetings: Meeting[] = [
  {
    id: 'meet-001',
    title: 'Annual General Meeting 2024',
    type: 'agm',
    date: '2024-03-15',
    time: '18:30',
    location: 'Community Room',
    isVirtual: true,
    meetingLink: 'https://zoom.us/j/example',
    status: 'scheduled',
    organizer: '1',
    attendees: ['1', '2', '3'],
    agenda: [
      {
        id: 'ag-001',
        title: 'Call to Order & Approval of Agenda',
        duration: 10,
        presenter: '1',
        order: 1,
      },
      {
        id: 'ag-002',
        title: 'Financial Report 2023',
        description: 'Review of annual financial statements and budget performance',
        duration: 30,
        presenter: '2',
        order: 2,
      },
      {
        id: 'ag-003',
        title: 'Major Maintenance Projects Update',
        description: 'Status of building envelope repair and HVAC upgrades',
        duration: 25,
        presenter: '3',
        order: 3,
      },
      {
        id: 'ag-004',
        title: 'Proposed Bylaw Amendments',
        description: 'Discussion on pet policy and rental restrictions',
        duration: 40,
        presenter: '1',
        order: 4,
      },
      {
        id: 'ag-005',
        title: 'Election of Council Members',
        duration: 30,
        presenter: '1',
        order: 5,
      },
    ],
    documents: [
      {
        id: 'doc-agm-001',
        name: 'AGM-Package-2024.pdf',
        type: 'application/pdf',
        size: 1245000,
        url: '/documents/agm-package.pdf',
        uploadedDate: '2024-02-28T10:00:00Z',
      },
    ],
  },
  {
    id: 'meet-002',
    title: 'Council Meeting - February',
    type: 'council',
    date: '2024-02-20',
    time: '19:00',
    location: 'Virtual',
    isVirtual: true,
    meetingLink: 'https://zoom.us/j/example',
    status: 'scheduled',
    organizer: '1',
    attendees: ['1', '2'],
    agenda: [
      {
        id: 'ag-006',
        title: 'Review Outstanding Maintenance Requests',
        duration: 20,
        presenter: '3',
        order: 1,
      },
      {
        id: 'ag-007',
        title: 'Violation Cases Update',
        duration: 15,
        presenter: '1',
        order: 2,
      },
      {
        id: 'ag-008',
        title: 'Budget Review Q1',
        duration: 25,
        presenter: '2',
        order: 3,
      },
    ],
  },
];

// Tasks
export const mockTasks: Task[] = [
  {
    id: 'task-001',
    title: 'Review Insurance Policy Renewal',
    description: 'Annual building insurance policy expires March 31. Need to review quotes from three providers.',
    status: 'inprogress',
    priority: 'high',
    assignedTo: ['2'],
    createdBy: '1',
    createdDate: '2024-02-01T09:00:00Z',
    dueDate: '2024-03-01T17:00:00Z',
    category: 'Administrative',
    tags: ['insurance', 'financial', 'urgent'],
    progress: 60,
    subtasks: [
      { id: 'st-001', title: 'Request quotes from current provider', completed: true },
      { id: 'st-002', title: 'Research alternative providers', completed: true },
      { id: 'st-003', title: 'Compare coverage and pricing', completed: false },
      { id: 'st-004', title: 'Present recommendation to council', completed: false },
    ],
  },
  {
    id: 'task-002',
    title: 'Organize Spring Community BBQ',
    description: 'Plan annual spring BBQ event for residents - coordinate date, vendors, budget.',
    status: 'todo',
    priority: 'medium',
    assignedTo: ['1'],
    createdBy: '1',
    createdDate: '2024-02-05T10:30:00Z',
    dueDate: '2024-04-15T17:00:00Z',
    category: 'Community Events',
    tags: ['event', 'community'],
    progress: 15,
    subtasks: [
      { id: 'st-005', title: 'Poll residents for preferred date', completed: true },
      { id: 'st-006', title: 'Book catering service', completed: false },
      { id: 'st-007', title: 'Reserve amenity space', completed: false },
      { id: 'st-008', title: 'Create promotional materials', completed: false },
    ],
  },
  {
    id: 'task-003',
    title: 'Update Emergency Contact List',
    description: 'Verify all emergency contacts are current and distribute updated list to residents.',
    status: 'review',
    priority: 'medium',
    assignedTo: ['3'],
    createdBy: '1',
    createdDate: '2024-01-20T14:00:00Z',
    dueDate: '2024-02-28T17:00:00Z',
    category: 'Safety & Security',
    tags: ['emergency', 'safety'],
    progress: 85,
  },
  {
    id: 'task-004',
    title: 'Prepare AGM Financial Report',
    description: 'Compile financial statements, budget vs. actual, and prepare presentation for AGM.',
    status: 'inprogress',
    priority: 'urgent',
    assignedTo: ['2'],
    createdBy: '1',
    createdDate: '2024-02-10T08:00:00Z',
    dueDate: '2024-03-10T17:00:00Z',
    category: 'Financial',
    tags: ['agm', 'financial', 'reporting'],
    progress: 40,
  },
];

// Documents
export const mockDocuments: Document[] = [
  {
    id: 'doc-001',
    title: 'Strata Bylaws - Updated 2024',
    type: 'bylaw',
    category: 'Governance',
    uploadedBy: '1',
    uploadedDate: '2024-01-15T10:00:00Z',
    lastModified: '2024-01-15T10:00:00Z',
    version: '3.0',
    size: 524288,
    fileType: 'PDF',
    url: '/documents/bylaws-2024.pdf',
    isPublic: true,
    accessLevel: 'all',
    tags: ['bylaws', 'governance', 'policies'],
    description: 'Complete set of strata bylaws including recent pet policy amendments.',
  },
  {
    id: 'doc-002',
    title: 'Annual Financial Statements 2023',
    type: 'financial',
    category: 'Financial',
    uploadedBy: '2',
    uploadedDate: '2024-01-30T14:30:00Z',
    lastModified: '2024-01-30T14:30:00Z',
    version: '1.0',
    size: 1048576,
    fileType: 'PDF',
    url: '/documents/financial-2023.pdf',
    isPublic: false,
    accessLevel: 'council',
    tags: ['financial', 'annual', 'statements'],
    description: 'Audited financial statements for fiscal year 2023.',
  },
  {
    id: 'doc-003',
    title: 'Building Insurance Policy',
    type: 'insurance',
    category: 'Insurance',
    uploadedBy: '3',
    uploadedDate: '2023-03-15T09:00:00Z',
    lastModified: '2023-03-15T09:00:00Z',
    version: '2023',
    size: 786432,
    fileType: 'PDF',
    url: '/documents/insurance-policy.pdf',
    isPublic: false,
    accessLevel: 'council',
    tags: ['insurance', 'policy'],
    description: 'Comprehensive building insurance policy with liability coverage.',
  },
  {
    id: 'doc-004',
    title: 'Resident Handbook',
    type: 'policy',
    category: 'Policies',
    uploadedBy: '1',
    uploadedDate: '2024-01-05T11:00:00Z',
    lastModified: '2024-01-05T11:00:00Z',
    version: '2.1',
    size: 314572,
    fileType: 'PDF',
    url: '/documents/resident-handbook.pdf',
    isPublic: true,
    accessLevel: 'all',
    tags: ['handbook', 'guide', 'residents'],
    description: 'Welcome guide for new residents with building rules and amenity information.',
  },
];

// Polls
export const mockPolls: Poll[] = [
  {
    id: 'poll-001',
    title: 'Preferred Date for Spring BBQ Event',
    description: 'Help us choose the best date for our annual community BBQ! Select your preferred weekend.',
    type: 'single_choice',
    status: 'active',
    createdBy: '1',
    createdDate: '2024-02-05T09:00:00Z',
    startDate: '2024-02-05T09:00:00Z',
    endDate: '2024-02-25T23:59:00Z',
    targetAudience: 'all_residents',
    options: [
      { id: 'opt-001', text: 'Saturday, April 20th', votes: 42, percentage: 45 },
      { id: 'opt-002', text: 'Sunday, April 21st', votes: 28, percentage: 30 },
      { id: 'opt-003', text: 'Saturday, April 27th', votes: 23, percentage: 25 },
    ],
    totalVotes: 93,
    isAnonymous: false,
    requiresQuorum: false,
  },
  {
    id: 'poll-002',
    title: 'Approve Special Levy for Building Envelope Repair',
    description: 'Council recommends a special levy of $5,000 per unit to fund critical building envelope repairs. This is a binding vote requiring 75% approval.',
    type: 'yes_no',
    status: 'active',
    createdBy: '1',
    createdDate: '2024-02-12T10:00:00Z',
    startDate: '2024-02-12T10:00:00Z',
    endDate: '2024-03-12T23:59:00Z',
    targetAudience: 'owners_only',
    options: [
      { id: 'opt-004', text: 'Approve Special Levy', votes: 68, percentage: 72 },
      { id: 'opt-005', text: 'Reject Special Levy', votes: 26, percentage: 28 },
    ],
    totalVotes: 94,
    isAnonymous: true,
    requiresQuorum: true,
    quorumPercentage: 50,
  },
  {
    id: 'poll-003',
    title: 'Gym Equipment Upgrade Priorities',
    description: 'We have budget for new gym equipment. Select up to 3 items you would most like to see added.',
    type: 'multiple_choice',
    status: 'active',
    createdBy: '1',
    createdDate: '2024-02-08T14:00:00Z',
    startDate: '2024-02-08T14:00:00Z',
    endDate: '2024-02-29T23:59:00Z',
    targetAudience: 'all_residents',
    options: [
      { id: 'opt-006', text: 'New Treadmills', votes: 67, percentage: 35 },
      { id: 'opt-007', text: 'Weight Bench Set', votes: 52, percentage: 27 },
      { id: 'opt-008', text: 'Rowing Machines', votes: 38, percentage: 20 },
      { id: 'opt-009', text: 'Yoga Mats & Equipment', votes: 34, percentage: 18 },
    ],
    totalVotes: 191,
    isAnonymous: false,
    requiresQuorum: false,
  },
];

// Amenities
export const mockAmenities: Amenity[] = [
  {
    id: 'amen-001',
    name: 'Rooftop Lounge',
    type: 'rooftop',
    description: 'Spectacular rooftop space with panoramic city and ocean views, BBQ stations, and comfortable seating.',
    capacity: 50,
    bookingDuration: 4,
    advanceBookingDays: 30,
    openingHours: '08:00',
    closingHours: '23:00',
    daysAvailable: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    amenities: ['BBQ Grills', 'Outdoor Furniture', 'Fire Pit', 'Sound System'],
    rules: [
      'Maximum 50 guests',
      'No glass bottles allowed',
      'Music must end by 10 PM',
      'Clean up required after use',
      'Reserve at least 3 days in advance',
    ],
    deposit: 200,
    hourlyRate: 0,
    images: ['/amenities/rooftop-1.jpg', '/amenities/rooftop-2.jpg'],
    isActive: true,
  },
  {
    id: 'amen-002',
    name: 'Guest Suite',
    type: 'guest_suite',
    description: 'Comfortable one-bedroom suite for visiting guests. Includes full kitchen, bathroom, and living area.',
    capacity: 4,
    bookingDuration: 24,
    advanceBookingDays: 60,
    openingHours: '15:00',
    closingHours: '11:00',
    daysAvailable: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    amenities: ['Full Kitchen', 'Queen Bed', 'Sofa Bed', 'WiFi', 'TV', 'Linens Provided'],
    rules: [
      'Maximum 3 night stay',
      'Check-in after 3 PM',
      'Check-out by 11 AM',
      'No smoking',
      'No pets',
      'Must be booked by a resident',
    ],
    deposit: 100,
    hourlyRate: 75,
    images: ['/amenities/guest-suite-1.jpg'],
    isActive: true,
  },
  {
    id: 'amen-003',
    name: 'Party Room',
    type: 'party_room',
    description: 'Spacious party room perfect for celebrations, complete with kitchen facilities and entertainment setup.',
    capacity: 40,
    bookingDuration: 6,
    advanceBookingDays: 45,
    openingHours: '09:00',
    closingHours: '01:00',
    daysAvailable: ['Friday', 'Saturday', 'Sunday'],
    amenities: ['Full Kitchen', 'Tables & Chairs', 'Projector', 'Sound System', 'Dance Floor'],
    rules: [
      'Maximum 40 guests',
      'Resident must be present at all times',
      'Noise restrictions after midnight',
      'Kitchen must be cleaned',
      'Garbage must be removed',
    ],
    deposit: 250,
    hourlyRate: 50,
    images: ['/amenities/party-room-1.jpg'],
    isActive: true,
  },
  {
    id: 'amen-004',
    name: 'Fitness Center',
    type: 'gym',
    description: 'Fully equipped gym with cardio machines, free weights, and strength training equipment.',
    capacity: 15,
    bookingDuration: 2,
    advanceBookingDays: 7,
    openingHours: '06:00',
    closingHours: '23:00',
    daysAvailable: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    amenities: ['Treadmills', 'Exercise Bikes', 'Free Weights', 'Weight Machines', 'Yoga Mats'],
    rules: [
      'Wipe down equipment after use',
      'Proper athletic footwear required',
      'No dropping weights',
      'Return equipment to proper place',
      'Maximum 2 hour sessions during peak times',
    ],
    deposit: 0,
    hourlyRate: 0,
    images: ['/amenities/gym-1.jpg'],
    isActive: true,
  },
];

// Bookings
export const mockBookings: Booking[] = [
  {
    id: 'book-001',
    amenityId: 'amen-001',
    amenityName: 'Rooftop Lounge',
    userId: '4',
    userName: 'James Thompson',
    unit: '508',
    date: '2024-03-09',
    startTime: '17:00',
    endTime: '21:00',
    status: 'confirmed',
    purpose: 'Birthday Celebration',
    guests: 25,
    specialRequests: 'Would like to use the fire pit',
    depositPaid: true,
    createdDate: '2024-02-10T14:30:00Z',
  },
  {
    id: 'book-002',
    amenityId: 'amen-002',
    amenityName: 'Guest Suite',
    userId: '5',
    userName: 'Emily Foster',
    unit: '612',
    date: '2024-02-25',
    startTime: '15:00',
    endTime: '11:00',
    status: 'confirmed',
    purpose: 'Parents visiting from out of town',
    guests: 2,
    depositPaid: true,
    createdDate: '2024-02-05T09:15:00Z',
  },
  {
    id: 'book-003',
    amenityId: 'amen-003',
    amenityName: 'Party Room',
    userId: '1',
    userName: 'Sarah Mitchell',
    unit: '405',
    date: '2024-03-16',
    startTime: '18:00',
    endTime: '24:00',
    status: 'pending',
    purpose: 'Family Gathering',
    guests: 30,
    depositPaid: false,
    createdDate: '2024-02-16T11:00:00Z',
  },
];

// Forum Posts
export const mockForumPosts: ForumPost[] = [
  {
    id: 'post-001',
    title: 'Best Local Restaurants Recommendations?',
    content: 'Just moved in last month and looking for good restaurant recommendations in the area. What are your favorites?',
    category: 'general',
    author: 'Emily Foster',
    authorId: '5',
    createdDate: '2024-02-14T10:30:00Z',
    lastActivity: '2024-02-16T14:20:00Z',
    views: 127,
    replies: 15,
    isPinned: false,
    isLocked: false,
    tags: ['recommendations', 'dining', 'local'],
  },
  {
    id: 'post-002',
    title: 'Reminder: AGM Coming Up March 15th',
    content: 'This is a reminder that our Annual General Meeting is scheduled for March 15th at 6:30 PM. The AGM package has been distributed. Please review and come prepared with questions.',
    category: 'general',
    author: 'Sarah Mitchell',
    authorId: '1',
    createdDate: '2024-02-12T09:00:00Z',
    lastActivity: '2024-02-15T16:45:00Z',
    views: 234,
    replies: 8,
    isPinned: true,
    isLocked: false,
    tags: ['agm', 'meeting', 'important'],
  },
  {
    id: 'post-003',
    title: 'Selling: Queen Size Bed Frame',
    content: 'Moving to a smaller unit. Selling a queen size bed frame in excellent condition. $150 OBO. Available for pickup this weekend.',
    category: 'marketplace',
    author: 'James Thompson',
    authorId: '4',
    createdDate: '2024-02-10T19:20:00Z',
    lastActivity: '2024-02-11T08:30:00Z',
    views: 89,
    replies: 5,
    isPinned: false,
    isLocked: false,
    tags: ['for-sale', 'furniture'],
  },
  {
    id: 'post-004',
    title: 'Noise Issue - Floor 8',
    content: 'Has anyone else on floor 8 been hearing construction-like noises in the evening? Trying to figure out where it is coming from.',
    category: 'questions',
    author: 'Unit 805 Resident',
    authorId: '6',
    createdDate: '2024-02-08T20:15:00Z',
    lastActivity: '2024-02-09T11:00:00Z',
    views: 156,
    replies: 12,
    isPinned: false,
    isLocked: false,
    tags: ['noise', 'question'],
  },
];

// Service Providers
export const mockServiceProviders: ServiceProvider[] = [
  {
    id: 'vendor-001',
    name: 'Precision Plumbing Services',
    category: 'plumber',
    description: 'Licensed plumbing contractor specializing in residential and commercial properties. 24/7 emergency service available.',
    contact: {
      phone: '(604) 555-7890',
      email: 'info@precisionplumbing.com',
      website: 'www.precisionplumbing.com',
    },
    address: '456 Industrial Way, Vancouver, BC',
    rating: 4.8,
    reviewCount: 47,
    services: ['Emergency Repairs', 'Pipe Installation', 'Drain Cleaning', 'Fixture Installation', 'Water Heater Service'],
    availability: 'Mon-Sun, 24/7 Emergency',
    hourlyRate: 95,
    insurance: true,
    licensed: true,
    preferredVendor: true,
    lastUsed: '2024-02-01',
  },
  {
    id: 'vendor-002',
    name: 'Bright Sparks Electrical',
    category: 'electrician',
    description: 'Certified electricians providing comprehensive electrical services for multi-unit residential buildings.',
    contact: {
      phone: '(604) 555-7891',
      email: 'service@brightsparks.com',
      website: 'www.brightsparks.com',
    },
    address: '789 Electric Ave, Burnaby, BC',
    rating: 4.9,
    reviewCount: 62,
    services: ['Electrical Repairs', 'Panel Upgrades', 'Lighting Installation', 'Safety Inspections', 'Emergency Service'],
    availability: 'Mon-Fri 7AM-7PM, Emergency 24/7',
    hourlyRate: 105,
    insurance: true,
    licensed: true,
    preferredVendor: true,
    lastUsed: '2024-02-15',
  },
  {
    id: 'vendor-003',
    name: 'GreenScape Landscaping',
    category: 'landscaping',
    description: 'Professional landscaping and grounds maintenance for commercial and residential properties.',
    contact: {
      phone: '(604) 555-7892',
      email: 'contact@greenscape.com',
    },
    address: '321 Garden Lane, Richmond, BC',
    rating: 4.6,
    reviewCount: 35,
    services: ['Lawn Maintenance', 'Garden Design', 'Irrigation Systems', 'Snow Removal', 'Tree Service'],
    availability: 'Mon-Sat 8AM-6PM',
    hourlyRate: 75,
    insurance: true,
    licensed: true,
    preferredVendor: true,
    lastUsed: '2024-01-20',
  },
  {
    id: 'vendor-004',
    name: 'CleanPro Building Services',
    category: 'cleaning',
    description: 'Commercial cleaning services specializing in high-rise residential buildings and common areas.',
    contact: {
      phone: '(604) 555-7893',
      email: 'bookings@cleanpro.com',
      website: 'www.cleanpro.com',
    },
    address: '555 Service Road, Vancouver, BC',
    rating: 4.7,
    reviewCount: 53,
    services: ['Common Area Cleaning', 'Carpet Cleaning', 'Window Washing', 'Pressure Washing', 'Move-Out Cleaning'],
    availability: 'Mon-Fri 8AM-5PM',
    hourlyRate: 55,
    insurance: true,
    licensed: true,
    preferredVendor: true,
    lastUsed: '2024-02-12',
  },
  {
    id: 'vendor-005',
    name: 'HVAC Masters',
    category: 'hvac',
    description: 'Heating, ventilation, and air conditioning specialists for residential and commercial buildings.',
    contact: {
      phone: '(604) 555-7894',
      email: 'service@hvacmasters.com',
      website: 'www.hvacmasters.com',
    },
    address: '888 Comfort Drive, Coquitlam, BC',
    rating: 4.8,
    reviewCount: 41,
    services: ['HVAC Repair', 'System Installation', 'Maintenance Plans', 'Air Quality Testing', 'Emergency Service'],
    availability: 'Mon-Sun, 24/7 Emergency',
    hourlyRate: 120,
    insurance: true,
    licensed: true,
    preferredVendor: false,
    lastUsed: '2023-11-15',
  },
];

// Emergency Contacts
export const mockEmergencyContacts: EmergencyContact[] = [
  {
    id: 'emerg-001',
    name: 'Emergency Services (Fire/Police/Ambulance)',
    type: 'emergency_services',
    phone: '911',
    available247: true,
    description: 'For life-threatening emergencies',
    order: 1,
  },
  {
    id: 'emerg-002',
    name: 'Building Security',
    type: 'security',
    phone: '(604) 555-8000',
    available247: true,
    description: '24/7 on-site security desk',
    order: 2,
  },
  {
    id: 'emerg-003',
    name: 'Property Manager - Linda Rodriguez',
    type: 'property_manager',
    phone: '(604) 555-0125',
    email: 'linda.rodriguez@email.com',
    available247: false,
    description: 'Mon-Fri 9AM-5PM, Emergency line available',
    order: 3,
  },
  {
    id: 'emerg-004',
    name: 'Council President - Sarah Mitchell',
    type: 'council',
    phone: '(604) 555-0123',
    email: 'sarah.mitchell@email.com',
    available247: false,
    description: 'For urgent council matters',
    order: 4,
  },
  {
    id: 'emerg-005',
    name: 'Emergency Plumber - Precision Plumbing',
    type: 'maintenance',
    phone: '(604) 555-7890',
    email: 'emergency@precisionplumbing.com',
    available247: true,
    description: '24/7 plumbing emergencies',
    order: 5,
  },
  {
    id: 'emerg-006',
    name: 'Emergency Electrician - Bright Sparks',
    type: 'maintenance',
    phone: '(604) 555-7891',
    email: 'emergency@brightsparks.com',
    available247: true,
    description: '24/7 electrical emergencies',
    order: 6,
  },
  {
    id: 'emerg-007',
    name: 'BC Hydro (Power Outages)',
    type: 'utility',
    phone: '1-800-BCHYDRO',
    available247: true,
    description: 'Report power outages',
    order: 7,
  },
  {
    id: 'emerg-008',
    name: 'Fortis BC (Gas Emergencies)',
    type: 'utility',
    phone: '1-800-663-9900',
    available247: true,
    description: 'Natural gas emergencies',
    order: 8,
  },
];

// Dashboard Stats - different for each role
export const mockDashboardStatsCouncil: DashboardStats = {
  pendingRequests: 12,
  activeViolations: 3,
  upcomingMeetings: 2,
  overdueTasksCount: 2,
  totalTasks: 8,
  completedThisMonth: 15,
  budgetUtilization: 68,
  activePolls: 3,
};

export const mockDashboardStatsManager: DashboardStats = {
  pendingRequests: 18,
  activeViolations: 5,
  upcomingMeetings: 1,
  overdueTasksCount: 3,
  totalTasks: 24,
  completedThisMonth: 42,
  budgetUtilization: 72,
  activePolls: 3,
};

export const mockDashboardStatsResident: DashboardStats = {
  pendingRequests: 1,
  activeViolations: 0,
  upcomingMeetings: 1,
  overdueTasksCount: 0,
  totalTasks: 0,
  completedThisMonth: 0,
  budgetUtilization: 0,
  activePolls: 2,
};

// Recent Activities
export const mockActivities: Activity[] = [
  {
    id: 'act-001',
    type: 'request',
    title: 'New Maintenance Request',
    description: 'Parking Garage Lighting Malfunction',
    date: '2024-02-15T09:30:00Z',
    user: 'James Thompson',
    status: 'in_progress',
    priority: 'urgent',
  },
  {
    id: 'act-002',
    type: 'poll',
    title: 'Poll Results',
    description: 'Spring BBQ date poll reached 90+ votes',
    date: '2024-02-14T16:45:00Z',
    user: 'Sarah Mitchell',
  },
  {
    id: 'act-003',
    type: 'violation',
    title: 'Violation Resolved',
    description: 'Improper Garbage Disposal - Unit 405',
    date: '2024-02-14T10:00:00Z',
    user: 'Linda Rodriguez',
    status: 'resolved',
  },
  {
    id: 'act-004',
    type: 'document',
    title: 'Document Uploaded',
    description: 'Strata Bylaws - Updated 2024',
    date: '2024-02-13T11:20:00Z',
    user: 'Sarah Mitchell',
  },
  {
    id: 'act-005',
    type: 'task',
    title: 'Task Completed',
    description: 'Update Emergency Contact List',
    date: '2024-02-12T14:30:00Z',
    user: 'Linda Rodriguez',
    status: 'completed',
  },
  {
    id: 'act-006',
    type: 'booking',
    title: 'Amenity Booked',
    description: 'Rooftop Lounge - March 9th',
    date: '2024-02-10T14:30:00Z',
    user: 'James Thompson',
  },
  {
    id: 'act-007',
    type: 'meeting',
    title: 'Meeting Scheduled',
    description: 'Council Meeting - February',
    date: '2024-02-08T09:00:00Z',
    user: 'Sarah Mitchell',
  },
];

// Helper function to get user by ID
export const getUserById = (id: string): User | undefined => {
  return mockUsers.find((user) => user.id === id);
};

// Helper function to get user by role
export const getUsersByRole = (role: UserRole): User[] => {
  return mockUsers.filter((user) => user.role === role);
};
